project:
  type: website
  output-dir: docs
  resources: 
    - gilardi_cv.pdf

website:
  title: "Andrea Gilardi"
  site-url: https://agila5.github.io/
  description: "Andrea Gilardi's Academic Website"
  open-graph: 
    locale: en_UK
  twitter-card:
    creator: "@a_gilardi5"
  google-analytics: 
    tracking-id: "G-GMF8NSBKDY"
    storage: none
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About me"
        href: about.qmd
  search: false

format:
  html:
    theme: [sandstone, _variables.scss]
