---
title: "A spatio-temporal model for events on road networks: an application to ambulance interventions in Milan"
description: |
  Slides used for presenting at SIS-2021 conference. 
author:
  - name: Andrea Gilardi
    url: https://agila5.github.io/
    affiliation: University of Milano - Bicocca
    orcid_id: 0000-0002-9424-7439
  - name: Riccardo Borgoni
    url: https://www.unimib.it/riccardo-borgoni
    affiliation: University of Milano - Bicocca
    orcid_id: 0000-0002-2520-3512
  - name: Jorge Mateu
    url: https://www3.uji.es/~mateu/
    affiliation: Universitat Jaume I
    orcid_id: 0000-0002-2868-7604
output:
  distill::distill_article:
    self_contained: false
draft: false
date: 2021-06-25
citation: false
categories:
  - Spatial Statistics 
  - Point patterns on road networks
preview: figures/milan.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following slides were used to present at the [SIS 2021](https://meetings3.sis-statistica.org/index.php/sis2021/sis2021) conference. 
Get <a href="https://docs.google.com/viewer?url=https://raw.githubusercontent.com/agila5/agila5.github.io/master/data/presentations/2021-06-25-SIS2021/SIS2021.pdf" target="_blank" rel="nopener">slides</a>. 

Abstract: The algorithms for optimal management and deployment of ambulances within a municipality require a spatio-temporal model to forecast hotspots and minimise the response times. Ambulance interventions represent an example of a point pattern occurring on a linear network, which was created starting from the main streets of Milan. The constrained spatial domain raises particular challenges and unique methodological problems that cannot be ignored for proper model development. Hence, this paper presents a non-separable spatio-temporal model for analysing the emergency interventions that occurred in the street network of Milan from 2015 to 2017. A dynamic latent factor model is adopted for capturing the temporal evolution, while the spatial dynamics are modelled using a network readaptation of a kernel estimator.
